### ISSUE TITLE
Error with importing GPflow

### ISSUE THREAD

**Issue by Este1le** [GPflow/GPflow#1010]
Hi,

I can install gpflow successfully, but I got the following error messages when I tried to import it.
___

## System information:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gpflow/_settings.py", line 35, in __getattr__
    return self._cur_settings[name]
KeyError: 'logging'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ssl_exp.py", line 3, in <module>
    from ggp.utils import *
  File "/Users/xuanzhang/Documents/research/GGP/ggp/utils.py", line 8, in <module>
    import gpflow as GPflow
  File "/usr/local/lib/python3.7/site-packages/gpflow/__init__.py", line 21, in <module>
    from .session_manager import get_session
  File "/usr/local/lib/python3.7/site-packages/gpflow/session_manager.py", line 24, in <module>
    logger = settings.logger()
  File "/usr/local/lib/python3.7/site-packages/gpflow/_settings.py", line 74, in logger
    level = logging.getLevelName(self.logging.level)
  File "/usr/local/lib/python3.7/site-packages/gpflow/_settings.py", line 37, in __getattr__
    raise AttributeError("Unknown setting.")
AttributeError: Unknown setting.
```

* Python version: 3.7.3
* TensorFlow installed from (source or binary): source
* TensorFlow version (use command below): v1.14.0-rc1-22-gaf24dc91b5 1.14.0
* GPflow installed from (source or binary): source
* GPflow version: 1.4.1

## Code to reproduce the issue
```
git clone https://github.com/GPflow/GPflow.git
cd GPflow
git checkout master
python3 setup.py install
python3
import gpflow
```

**Comment by markvdw** [comment]
I would recommend using the develop branch. If this is still a problem, let us know with the gpflow tag on stackoverflow!
