### ISSUE TITLE
Tensorflow serving with gpflow

### ISSUE THREAD

**Issue by phy-reac** [GPflow/GPflow#1021]
Hi all,

I am new to gpflow and am interested in coregionalisation. I am sorry if I am replicating an old issue here. I was trying to create a TF serving api - for which I have managed to get a minimum working example running (see below). As was expected, the memory size of protobuf file, which stores the metagraph(s), starts to grow rapidly as the kernel complexity is increased. I wondered if there is a way or a feature which could strip away the unnecessary components of the metagraphs which are not required for serving. The objective is to reduce the memory size of the saved model files, and I suppose there are other tactics that can be used just as well. For e.g., I am not sure, but is it possible to throw away components related to the output observations in coregionalisation which will not be used for serving before saving the .pb? I have also tried switching from float64 to float32 via gpflowrc, but got an error. Please see below.

Thank you very much.

> gpflow '1.4.1'
> tensorflow '1.14.0'
> numpy '1.15.2'

```
MWE:
#######
import gpflow
from gpflow import settings
import numpy as np
import tensorflow as tf

#### based on the example in the readdocs (serving part pinched from Joachim van der Herten #### blog )
# synthetic data
X1 = np.random.rand(100, 1)
X2 = np.random.rand(50, 1) * 0.5
Y1 = np.sin(6*X1) + np.random.standard_t(3, X1.shape)*0.03
Y2 = np.sin(6*X2+ 0.7) + np.random.standard_t(3, X2.shape)*0.1
X_augmented = np.vstack((np.hstack((X1, np.zeros_like(X1))), np.hstack((X2, np.ones_like(X2)))))
Y_augmented = np.vstack((np.hstack((Y1, np.zeros_like(X1))), np.hstack((Y2, np.ones_like(X2)))))

# input and output tensors for serving
inputs = [('Xnew', (gpflow.settings.float_type, [None, None]))]
outputs = ['mean', 'variance']

# force dtypes
X_augmented = np.array( X_augmented, dtype=settings.float_type )
Y_augmented = np.array( Y_augmented, dtype=settings.float_type )

def build_model(X_augmented, Y_augmented, rank=1):
    k1 = gpflow.kernels.Matern32(1, active_dims=[0])
    coreg = gpflow.kernels.Coregion(1, output_dim=2, rank=rank, active_dims=[1])
    kern = k1 * coreg
    lik = gpflow.likelihoods.SwitchedLikelihood([gpflow.likelihoods.StudentT(), gpflow.likelihoods.StudentT()])
    m = gpflow.models.VGP(X_augmented, Y_augmented, kern=kern, likelihood=lik, num_latent=1)
#    m.kern.coregion.W =np.random.randn(len(np.unique(Y_augmented[:, -1])),
#            rank)
    gpflow.train.ScipyOptimizer().minimize(m)
    return m

def save_build_method(method, inputs, outputs, export_dir='model'):
   # Get the model instance from the bound method
   obj = method.__self__
   assert isinstance(obj, gpflow.models.Model)

   sess = obj.enquire_session(session=None)
   with sess.graph.as_default():
       # Create placeholders for the inputs (much like the AutoFlow decorator)
       names, specs = zip(*inputs)
       arguments = [tf.placeholder(*spec) for spec in specs]

       # Obtain the output tensor(s)
       result = method(*arguments)
       assert len(result) == len(outputs)

       # Initialize the graph
       obj.initialize(session=sess, force=False)

       # For the export we need to create build_tensor_info for the I/O
       inputs_info = dict(zip(names, map(tf.saved_model.utils.build_tensor_info, arguments)))
       outputs_info = dict(zip(outputs, map(tf.saved_model.utils.build_tensor_info, result)))
       # Create the signature definition
       signature_def = tf.saved_model.signature_def_utils.build_signature_def(
           inputs=inputs_info,
           outputs=outputs_info,
           method_name=tf.saved_model.signature_constants.PREDICT_METHOD_NAME
       )

       signature_def_map = {
           tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY: signature_def
       }
       # Now we are ready to export the graph along with the session values
       # The SavedModel is saved in its own directory
       builder = tf.saved_model.builder.SavedModelBuilder(export_dir)
       builder.add_meta_graph_and_variables(sess,
                                            [tf.saved_model.tag_constants.SERVING],
                                            signature_def_map=signature_def_map,
                                            strip_default_attrs=True)
       builder.save()
if __name__ == "__main__":
    mod =build_model(X_augmented=X_augmented, Y_augmented=Y_augmented)
    save_build_method(method=mod._build_predict, inputs=inputs, outputs=outputs,
        export_dir='./model')
```

```
[logging]
# possible levels: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET
level = WARNING
[verbosity]
tf_compile_verb = False
[dtypes]
float_type = float32
int_type = int32
[numerics]
jitter_level = 1e-3
# quadrature can be set to: allow, warn, error
ekern_quadrature = warn
[profiling]
dump_timeline = False
dump_tensorboard = False
output_file_name = timeline
output_directory = ./
each_time = False
[session]
intra_op_parallelism_threads = 0
inter_op_parallelism_threads = 0
```

```
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/tf_gpu14_p35/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 527, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/usr/local/anaconda3/envs/tf_gpu14_p35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1224, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/anaconda3/envs/tf_gpu14_p35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1018, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype float64 for Tensor with dtype float32: 'Tensor("VGP-4a153079-16/gauss_kl/Neg:0", shape=(), dtype=float32)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "TA_corr.py", line 66, in <module>
    mod =build_model(X_augmented=X_augmented, Y_augmented=Y_augmented)
  File "TA_corr.py", line 20, in build_model
    m = gpflow.models.VGP(X_augmented, Y_augmented, kern=kern, likelihood=lik, num_latent=1)
  File "</usr/local/anaconda3/envs/tf_gpu14_p35/lib/python3.5/site-packages/decorator.py:decorator-gen-58>", line 2, in __init__
  File "/usr/local/anaconda3/envs/tf_gpu14_p35/lib/python3.5/site-packages/gpflow-1.4.1-py3.5.egg/gpflow/core/compilable.py", line 156, in init_wrapper
    self.build()
  File "/usr/local/anaconda3/envs/tf_gpu14_p35/lib/python3.5/site-packages/gpflow-1.4.1-py3.5.egg/gpflow/core/node.py", line 156, in build
    self._build()
  File "/usr/local/anaconda3/envs/tf_gpu14_p35/lib/python3.5/site-packages/gpflow-1.4.1-py3.5.egg/gpflow/models/vgp.py", line 92, in _build
    return super()._build()
  File "/usr/local/anaconda3/envs/tf_gpu14_p35/lib/python3.5/site-packages/gpflow-1.4.1-py3.5.egg/gpflow/models/model.py", line 80, in _build
    likelihood = self._build_likelihood()
  File "/usr/local/anaconda3/envs/tf_gpu14_p35/lib/python3.5/site-packages/gpflow-1.4.1-py3.5.egg/gpflow/decors.py", line 67, in tensor_mode_wrapper
    result = method(obj, *args, **kwargs)
  File "/usr/local/anaconda3/envs/tf_gpu14_p35/lib/python3.5/site-packages/gpflow-1.4.1-py3.5.egg/gpflow/models/vgp.py", line 109, in _build_likelihood
    KL = gauss_kl(self.q_mu, self.q_sqrt)
  File "/usr/local/anaconda3/envs/tf_gpu14_p35/lib/python3.5/site-packages/gpflow-1.4.1-py3.5.egg/gpflow/decors.py", line 49, in name_scope_wrapper
    return method(*args, **kwargs)
  File "/usr/local/anaconda3/envs/tf_gpu14_p35/lib/python3.5/site-packages/gpflow-1.4.1-py3.5.egg/gpflow/kullback_leiblers.py", line 106, in gauss_kl
    twoKL = mahalanobis + constant - logdet_qcov + trace
  File "/usr/local/anaconda3/envs/tf_gpu14_p35/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 884, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/anaconda3/envs/tf_gpu14_p35/lib/python3.5/site-packages/tensorflow/python/ops/gen_math_ops.py", line 387, in add
    "Add", x=x, y=y, name=name)
  File "/usr/local/anaconda3/envs/tf_gpu14_p35/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 563, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'y' of 'Add' Op has type float32 that does not match type float64 of argument 'x'.
```

**Comment by st--** [comment]
@phy-reac thanks for your interest in gpflow, and sorry for taking so long to reply!

I believe the float32 vs float64 issue is related to #802 ... it'd be great if you wanted to help fix that! it's just a matter of going through and making sure things are properly cast to the gpflow default_float dtype... you're very welcome to help out and make a PR! Ideally to the gpflow-2.0 code in `develop` :)

The remainder of your question is more suitable to stackoverflow: please post there under the gpflow tag https://stackoverflow.com/questions/tagged/gpflow and then any answers will be more helpful to other users!
