### ISSUE TITLE
Error when using tf dtypes as default float

### ISSUE THREAD

**Issue by joelberkeley-secondmind** [GPflow/GPflow#1596]
# Bug

When I use tf dtypes as default float, I encounter errors in gpflow code that tries to convert numpy array dtypes using the default float.

## To reproduce

```python
>>> with gpflow.config.as_context(gpflow.config.Config(float=tf.float64)):
...     gpflow.quadrature.gauss_hermite.gh_points_and_weights(1)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/.../lib/python3.7/site-packages/gpflow/quadrature/gauss_hermite.py", line 41, in gh_points_and_weights
    z, dz = z.astype(default_float()), dz.astype(default_float())
TypeError: data type not understood
```

## Expected behavior

I'd like gpflow to either accept tf types as default float, or warn me when I try to create the config. Note it might be a little strange to not support tf types on one hand and not explicitly support numpy arrays either

## System information

* GPflow version: 2.1.3
* GPflow installed from: pypi
* TensorFlow version: 2.3.1
* Python version: 3.7

**Comment by st--** [comment]
Ah, I had encountered this issue before and changed `set_default_float` and `set_default_int` to canonize the types to the numpy dtypes which works around these issues (TF accepts NumPy dtypes, but not vice versa). Didn't think of doing that for the Config creator. So we just need to go and do that.

**Comment by vdutor** [comment]
Hi @joelberkeley-secondmind, what's the current state of this issue, can it be closed?

**Comment by joelberkeley** [comment]
@vdutor if it's fixed, yes, but I don't have any reason to think it has been
