### ISSUE TITLE
Dimension reducing kernels.

### ISSUE THREAD

**Issue by SamTov** [GPflow/GPflow#1752]
# Feature request / Bug report

Not sure which it will come under as it is possible I am just doing something wrong in the pipeline.

## Motivation

In some GPR problems you may have a set of input values which are combined under some kernel to yield a single target. I believe in (GPR) literature this is referred to as a linear combination of function values problem. For example, I need to compute a kernel between two values `k(X, Y)` where `X = {x1, x2, x3, x4}` and `Y={y1, y2, y3, y4}`.

In this case, you can say:

```
k(X, Y) = sum over i, j k(xi, yj)
```

In GPFlow I have approached this problem by writing my own kernel function included at the bottom of this issue for reference. This kernel successfully performs the kernel operation described above for a dot-product. It is tested with the following:

```python
kernel = DotProduct(zeta=1)
        conf_1 = [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]  # shape (2, 3)
        conf_2 = [[4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]  # shape (2, 3)
        confs = tf.convert_to_tensor([conf_1, conf_2], dtype=tf.double)

        covariance_matrix = kernel.K(confs)  # shape (2, 2)
        diagonals = kernel.K_diag(confs)
        np.testing.assert_array_equal(covariance_matrix,
                                      np.array([[155., 281.], [281., 515.]]))
        np.testing.assert_array_equal(diagonals, np.array([155., 515.]))
```
So it reduces the dimension of the system such that you only get covariance between the two configurations as a sum over operations on the elements in each configuration. 

When I try to train the GP the input looks as follows:

```python
train_ds, test_ds = self._prepare_data()
        targets, configurations = self._build_model(train_ds)

        print(configurations.shape)  # == (5, 108, 50)

        k = DotProduct(zeta=4)

        print(k.K(configurations))  # shape (5, 5)
        print(k.K_diag(configurations))  # shape(5,)

        m = gpflow.models.GPR((configurations, targets), kernel=k)
        opt = gpflow.optimizers.Scipy()
        opt.minimize(m.training_loss, variables=m.trainable_variables)
        print_summary(m, fmt="notebook")

```
In this case, I pass 5 of these configurations and get a kernel out of the shape (5, 5) as it should. However, when the rest of the lines run I get the following error.

```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/s/S.Tovey/miniconda3/envs/zincware/lib/python3.8/site-packages/zntrack/core/decorator.py", line 282, in wrapper
    function = func(cls)
  File "/home/s/S.Tovey/work/Repositories/MLSuite/mlsuite/models/model.py", line 78, in run
    self.engine.fit()
  File "/home/s/S.Tovey/work/Repositories/MLSuite/mlsuite/models/gpr_pes.py", line 159, in fit
    opt.minimize(m.training_loss, variables=m.trainable_variables)
  File "/home/s/S.Tovey/miniconda3/envs/zincware/lib/python3.8/site-packages/gpflow/optimizers/scipy.py", line 90, in minimize
    return scipy.optimize.minimize(
  File "/home/s/S.Tovey/miniconda3/envs/zincware/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 623, in minimize
    return _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File "/home/s/S.Tovey/miniconda3/envs/zincware/lib/python3.8/site-packages/scipy/optimize/lbfgsb.py", line 306, in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
  File "/home/s/S.Tovey/miniconda3/envs/zincware/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/s/S.Tovey/miniconda3/envs/zincware/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 140, in __init__
    self._update_fun()
  File "/home/s/S.Tovey/miniconda3/envs/zincware/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 233, in _update_fun
    self._update_fun_impl()
  File "/home/s/S.Tovey/miniconda3/envs/zincware/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 137, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/s/S.Tovey/miniconda3/envs/zincware/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 134, in fun_wrapped
    return fun(np.copy(x), *args)
  File "/home/s/S.Tovey/miniconda3/envs/zincware/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/s/S.Tovey/miniconda3/envs/zincware/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/s/S.Tovey/miniconda3/envs/zincware/lib/python3.8/site-packages/gpflow/optimizers/scipy.py", line 113, in _eval
    loss, grad = _tf_eval(tf.convert_to_tensor(x))
  File "/home/s/S.Tovey/miniconda3/envs/zincware/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/s/S.Tovey/miniconda3/envs/zincware/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 1129, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    File "/home/s/S.Tovey/miniconda3/envs/zincware/lib/python3.8/site-packages/gpflow/optimizers/scipy.py", line 106, in _tf_eval  *
        loss, grads = _compute_loss_and_gradients(closure, variables)
    File "/home/s/S.Tovey/miniconda3/envs/zincware/lib/python3.8/site-packages/gpflow/optimizers/scipy.py", line 172, in _compute_loss_and_gradients  *
        loss = loss_closure()
    File "/home/s/S.Tovey/miniconda3/envs/zincware/lib/python3.8/site-packages/gpflow/models/training_mixins.py", line 63, in training_loss  *
        return self._training_loss()
    File "/home/s/S.Tovey/miniconda3/envs/zincware/lib/python3.8/site-packages/gpflow/models/model.py", line 56, in _training_loss  *
        return -(self.maximum_log_likelihood_objective(*args, **kwargs) + self.log_prior_density())
    File "/home/s/S.Tovey/miniconda3/envs/zincware/lib/python3.8/site-packages/gpflow/models/gpr.py", line 67, in maximum_log_likelihood_objective  *
        return self.log_marginal_likelihood()
    File "/home/s/S.Tovey/miniconda3/envs/zincware/lib/python3.8/site-packages/gpflow/models/gpr.py", line 91, in log_marginal_likelihood  *
        log_prob = multivariate_normal(Y, m, L)
    File "/home/s/S.Tovey/miniconda3/envs/zincware/lib/python3.8/site-packages/gpflow/logdensities.py", line 97, in multivariate_normal  *
        alpha = tf.linalg.triangular_solve(L, d, lower=True)

    ValueError: Dimensions must be equal, but are 5 and 108 for '{{node triangular_solve/MatrixTriangularSolve}} = MatrixTriangularSolve[T=DT_DOUBLE, adjoint=false, lower=true](Cholesky, sub)' with input shapes: [5,5], [5,108,5].

Process finished with exit code 1

```
As far as I can see, something is going wrong with the application of the kernel somewhere internally but I am unsure of exactly where to look as the kernel seems to work fine before the calling of the training and in the tests. 

I am writing this as a feature request as I am unsure of whether what I am trying to do violates something internal in GPFlow or whether I am just doing something wrong. If this is incompatibly with GPFlow then I think the ability to have dimension reducing kernels would be a great feature for the code and I would be happy to contribute to making that a reality. 

## Proposal

**Describe the solution you would like**
I would like this to train properly.

**What alternatives have you considered?**
I can do the operation without any GPFlow but would like to use the sparsification tools and other great things included in the package.

**Are you willing to open a pull request?** (We really appreciate contributions!)
Yes I would be happy to with some guidance of what might be going wrong.

## Kernel class

This is the dot product kernel 
```python
class DotProduct(gpf.kernels.Kernel):
    """
    Class for the dot product kernel computation using GPFlow
    """
    def __init__(self, zeta: float):
        """
        Constructor for the dot product kernel class.

        Parameters
        ----------
        zeta : float
                Sensitivity index to use in the computation.
        """
        super(DotProduct, self).__init__(active_dims=[0])
        self.zeta = zeta
        self.variance = gpf.Parameter(1.0, transform=positive())

    def K(self, X: tf.Tensor, X2: tf.Tensor = None):
        """
        Compute the covariance between matrices.

        Parameters
        ----------
        X : tf.Tensor
                Tensor 1
        X2 : tf.Tensor
                Tensor 2

        Returns
        -------
        covariance between these two points.
        """
        if X2 is None:
            X2 = X
        tensor_prod = tf.tensordot(X, tf.transpose(X2, perm=[0, 2, 1]), axes=0)
        K1 = tf.einsum('ijklkm -> ijlm', tensor_prod)
        K = tf.einsum('ijlm -> il', tf.pow(K1, self.zeta))

        return K

    def K_diag(self, X: tf.Tensor):
        """

        Parameters
        ----------
        X : tf.Tensor
                Tensor on which to perform the kernel operation.

        Returns
        -------

        """
        pre = self.K(X)
        mask = tf.eye(len(pre))
        return self.variance * tf.boolean_mask(pre, mask)
```

**Comment by SamTov** [comment]
@jameshensman @st--  Just wondering if anyone has any thoughts on this issue?

**Comment by st--** [comment]
@SamTov hi, thanks for the prod & apologies for not getting back to this sooner!

I think the issue is in the shapes:
```python
        print(configurations.shape)  # == (5, 108, 50)
```
GPR (and the other GPflow models) generally assume that `X` and `Y` are both rank-2 tensors (i.e., matrices), so `X.shape == (num_inputs, input_dim)` and `Y.shape == (num_inputs, output_dim)`.

Would it work if you reshape configurations to (5, 108*50), and you can re-shape them to whatever you need within your kernel definition?
Just remember to use the tensorflow ops:
```python
def K_diag(self, X):
    # X.shape == (5, 108*50)
    Xconf = tf.reshape(X, (-1, 108, 50))  # shape == (5, 108, 50)
    # do whatever you want with Xconf as before
    # ...
```
does that make sense?

NB- whilst you have to _implement_ `K` and `K_diag`, the convention is to _call_ the kernel object directly, i.e. `k(X)` or `k(X, diag=True)`.

**Comment by loggoman** [comment]
I have a similar issue, I get the model to run by using a custom mean function that gives the correct output shape for my data. However, the model does not optimize the inducing variables, it throws a warning that one variable is not connected to the loss_closure/has no gradient. I am using the SVGP model. 

Is there any way to make it work with a dimension-reducing kernel or would that require implementing a new model almost from scratch?

@st-- @jameshensman

**Comment by SamTov** [comment]
Just as it has been brought up again, I have not tried to implement this solution yet as it is not too urgent for me. However, this class of problems is quite general in the "linear combination of function values" sense. It would be interesting to consider aggregation functions or something similar in GPFlow as a means of performing this type of dimension reduction. In principle, I can define a kernel operation over an axis in a tensor and then an aggregation function to describe how that should then be reduced into a single value.

**Comment by micmicqb** [comment]
@SamTov Maybe I'm misunderstanding intention, but couldn't you simply specify kernels with different active dimensions, and then add them up?

E.g.,
`k = sum([gpflow.kernels.SquaredExponential(..., active_dims=[i]) for i in range(X.shape[1])])`

See https://gpflow.github.io/GPflow/develop/notebooks/advanced/kernels.html#Specify-active-dimensions

**Comment by SamTov** [comment]
@micmicqb Sounds exactly like what I was lookinhg for yes! Thank you for the answer.
