### ISSUE TITLE
Import error:  No module named 'tensorflow.compat'

### ISSUE THREAD

**Issue by medperdiem** [GPflow/GPflow#2035]
# ModuleNotFoundError: No module named 'tensorflow.compat' with import gpflow

When I try to import gpflow into a python script, I get an error message saying there is no tensorflow.compat module.  The latest stable release of tensorflow is installed, see output of *pip show tensorflow*
```
Name: tensorflow
Version: 2.11.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: c:\users\19493\appdata\roaming\python\python38\site-packages
Requires: tensorflow-intel
Required-by: basic-pitch, gpflow
```
As is the latest version of gpflow  - *pip show gpflow* output:
```
Name: gpflow
Version: 2.6.4
Summary: Gaussian process methods in TensorFlow
Home-page: https://www.gpflow.org
Author: James Hensman, Alex Matthews
Author-email: james.hensman@gmail.com
License: Apache License 2.0
Location: c:\users\19493\anaconda3\lib\site-packages
Requires: deprecated, lark, multipledispatch, numpy, packaging, scipy, setuptools, tabulate, tensorflow, tensorflow-probability, typing-extensions
Required-by:
```
## To reproduce

**Minimal, reproducible example**

```python
import gpflow
```

**Stack trace, or error message**
```
Failed to import TensorFlow. Please note that TensorFlow is not installed by default when you install TensorFlow Probability. This is so that users can decide whether to install the GPU-enabled TensorFlow package. To use TensorFlow Probability, please install the most recent version of TensorFlow, by following instructions at https://tensorflow.org/install.

Traceback (most recent call last):

  File "<ipython-input-26-0dccf67cb4c8>", line 1, in <module>
    import gpflow

  File "C:\Users\19493\anaconda3\lib\site-packages\gpflow\__init__.py", line 17, in <module>
    from . import (

  File "C:\Users\19493\anaconda3\lib\site-packages\gpflow\conditionals\__init__.py", line 1, in <module>
    from . import conditionals, multioutput, sample_conditionals

  File "C:\Users\19493\anaconda3\lib\site-packages\gpflow\conditionals\conditionals.py", line 19, in <module>
    from ..base import MeanAndVariance

  File "C:\Users\19493\anaconda3\lib\site-packages\gpflow\base.py", line 23, in <module>
    from .config import default_float, default_summary_fmt

  File "C:\Users\19493\anaconda3\lib\site-packages\gpflow\config\__init__.py", line 1, in <module>
    from .__config__ import *

  File "C:\Users\19493\anaconda3\lib\site-packages\gpflow\config\__config__.py", line 350, in <module>
    set_config(Config())

  File "<string>", line 6, in __init__

  File "C:\Users\19493\anaconda3\lib\site-packages\gpflow\config\__config__.py", line 139, in _default_positive_bijector_factory
    if bijector_type not in positive_bijector_type_map().keys():

  File "C:\Users\19493\anaconda3\lib\site-packages\gpflow\config\__config__.py", line 332, in positive_bijector_type_map
    "exp": tfp.bijectors.Exp,

  File "C:\Users\19493\anaconda3\lib\site-packages\tensorflow_probability\python\internal\lazy_loader.py", line 53, in __getattr__
    module = self._load()

  File "C:\Users\19493\anaconda3\lib\site-packages\tensorflow_probability\python\internal\lazy_loader.py", line 37, in _load
    self._on_first_access()

  File "C:\Users\19493\anaconda3\lib\site-packages\tensorflow_probability\python\__init__.py", line 38, in _validate_tf_environment
    import tensorflow.compat.v1 as tf

ModuleNotFoundError: No module named 'tensorflow.compat'
```

## Expected behavior
gpflow to interact with tensorflow as expected. I'm sure there's something obvious I'm missing.

## System information

* GPflow version:  2.6.4
* GPflow installed from:  pip install gpflow
* TensorFlow version: 2.11.0
* Python version:   3.8.8
* Operating system:  Windows 10

Appreciate any help you can provide.

**Comment by sc336** [comment]
Have you matched the TensorFlow and TensorFlow Probability versions as per this table:
https://gpflow.github.io/GPflow/develop/installation.html

**Comment by medperdiem** [comment]
Thanks, your table indicated GPflow may not be compatible with tensorflow 2.11.0.  I installed 2.10.0 instead and it works now.  Thanks again.
