### ISSUE TITLE
Kernel `active_dims` and lengthscales inconsistent shapes

### ISSUE THREAD

**Issue by schauma** [GPflow/GPflow#2122]
# Bug 

I want to reproduce the example in the [kernels](https://gpflow.github.io/GPflow/develop/notebooks/getting_started/kernels.html) documentation using multiple dimension. However the setting of a list of lengthscales results in an inconsistent shapes error from `tensorflow`.

## To reproduce

**Minimal, reproducible example**

```python
import numpy as np
import gpflow as gp


data = np.random.random((100,4))

kernel = gp.kernels.SquaredExponential(variance = 1e-3,lengthscales= np.array([0.1,0.1,0.1]),active_dims = [0,1,2])


k = kernel.K(data) # <-- Error
```

**Stack trace, or error message**
```
2024-10-30 19:12:31.444741: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: INVALID_ARGUMENT: Incompatible shapes: [100,4] vs. [3]
Traceback (most recent call last):
  File "/home/user/Documents/Software/Python/Notebooks/GaussianProcesses/scratch.py", line 12, in <module>
    k = kernel.K(data)
  File "/home/user/Documents/Software/Python/Notebooks/venv/lib/python3.10/site-packages/check_shapes/integration/tf.py", line 76, in wrapped_method
    return wrapped_function(self, *args, **kwargs)
  File "/home/user/Documents/Software/Python/Notebooks/venv/lib/python3.10/site-packages/gpflow/kernels/stationaries.py", line 104, in K
    r2 = self.scaled_squared_euclid_dist(X, X2)
  File "/home/user/Documents/Software/Python/Notebooks/venv/lib/python3.10/site-packages/check_shapes/integration/tf.py", line 76, in wrapped_method
    return wrapped_function(self, *args, **kwargs)
  File "/home/user/Documents/Software/Python/Notebooks/venv/lib/python3.10/site-packages/gpflow/kernels/stationaries.py", line 130, in scaled_squared_euclid_dist
    return square_distance(self.scale(X), self.scale(X2))
  File "/home/user/Documents/Software/Python/Notebooks/venv/lib/python3.10/site-packages/check_shapes/integration/tf.py", line 76, in wrapped_method
    return wrapped_function(self, *args, **kwargs)
  File "/home/user/Documents/Software/Python/Notebooks/venv/lib/python3.10/site-packages/gpflow/kernels/stationaries.py", line 78, in scale
    X_scaled = X / self.lengthscales if X is not None else X
  File "/home/user/Documents/Software/Python/Notebooks/venv/lib/python3.10/site-packages/tensorflow_probability/python/util/deferred_tensor.py", line 77, in new_fn_like_old_fn
    return old_fn(value, *args, **kwargs)
  File "/home/user/Documents/Software/Python/Notebooks/venv/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/user/Documents/Software/Python/Notebooks/venv/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 5983, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__RealDiv_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [100,4] vs. [3] [Op:RealDiv] name: 

Process finished with exit code 1
```

## Expected behavior

I expect the regular kernel matrix as if I supplied just a single float as the lengthscale. 

## System information

* GPflow version: 2.9.2
* GPflow installed from: pip
* TensorFlow version: 2.17.0
* Python version: 3.10.15 (main, Sep  7 2024, 18:35:38) [GCC 13.2.0] 
* Operating system: Ubuntu 24.04

**Comment by uri-granta** [comment]
Apologies for the slow response!

While it's true that the lengthscales all start off identical, you are still specifying a 3 dimensional kernel. It's therefore no surprise that it fails to work with 4 dimensional input. Or am I misunderstanding something?

**Comment by st--** [comment]
You should also call the kernel object directly, not its `.K` method. Correct would be: `kernel(data)`
