### ISSUE TITLE
Multiclass classification does not work with soft labels as input

### ISSUE THREAD

**Issue by ilia10000** [GPflow/GPflow#2123]
# Bug / performance issue / build issue

Size mismatch errors crop up when trying to run approximate inference for multiclass classification with soft label inputs. 

## To reproduce

**Minimal, reproducible example**

```python
import warnings

warnings.filterwarnings("ignore")  # ignore DeprecationWarnings from tensorflow

import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
# from multiclass_classification import colors, plot_posterior_predictions

import gpflow
from gpflow.ci_utils import reduce_in_tests
from gpflow.utilities import print_summary, set_trainable

%matplotlib inline


# reproducibility:
np.random.seed(0)
tf.random.set_seed(123)
X = np.array([5.,14.]).reshape((-1,1))
Y=np.array([[0.  , 0.  , 1.  ],
       [0.25, 0.5 , 0.25]])

data=(X,Y)
C=3

Z=X.copy()#np.array(list(range(0,20))).reshape((-1,1))

kernel = gpflow.kernels.Matern32() + gpflow.kernels.White(variance=0.01)

# Robustmax Multiclass Likelihood
invlink = gpflow.likelihoods.RobustMax(C)  # Robustmax inverse link function
likelihood = gpflow.likelihoods.MultiClass(
    3, invlink=invlink
)  # Multiclass likelihood
# Z = X[::5].copy()  # inducing inputs

m = gpflow.models.SVGP(
    kernel=kernel,
    likelihood=likelihood,
    inducing_variable=Z,
    num_latent_gps=C,
    whiten=True,
    q_diag=True,
)

# Only train the variational parameters
set_trainable(m.kernel.kernels[1].variance, False)
set_trainable(m.inducing_variable, False)

opt = gpflow.optimizers.Scipy()

opt_logs = opt.minimize(
    m.training_loss_closure(data),
    m.trainable_variables,
    options=dict(maxiter=reduce_in_tests(1000)),
)
print_summary(m, fmt="notebook")
```

**Stack trace, or error message**
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_210432/1705955573.py in <module>
      1 opt = gpflow.optimizers.Scipy()
      2 
----> 3 opt_logs = opt.minimize(
      4     m.training_loss_closure(data),
      5     m.trainable_variables,

~/anaconda3/lib/python3.9/site-packages/gpflow/optimizers/scipy.py in minimize(self, closure, variables, method, step_callback, compile, allow_unused_variables, tf_fun_args, track_loss_history, **scipy_kwargs)
    157             scipy_kwargs["callback"] = callback
    158 
--> 159         opt_result = scipy.optimize.minimize(
    160             func, initial_params, jac=True, method=method, **scipy_kwargs
    161         )

~/anaconda3/lib/python3.9/site-packages/scipy/optimize/_minimize.py in minimize(fun, x0, args, method, jac, hess, hessp, bounds, constraints, tol, callback, options)
    690                                  **options)
    691     elif meth == 'l-bfgs-b':
--> 692         res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
    693                                callback=callback, **options)
    694     elif meth == 'tnc':

~/anaconda3/lib/python3.9/site-packages/scipy/optimize/_lbfgsb_py.py in _minimize_lbfgsb(fun, x0, args, jac, bounds, disp, maxcor, ftol, gtol, eps, maxfun, maxiter, iprint, callback, maxls, finite_diff_rel_step, **unknown_options)
    306             iprint = disp
    307 
--> 308     sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
    309                                   bounds=new_bounds,
    310                                   finite_diff_rel_step=finite_diff_rel_step)

~/anaconda3/lib/python3.9/site-packages/scipy/optimize/_optimize.py in _prepare_scalar_function(fun, x0, jac, args, bounds, epsilon, finite_diff_rel_step, hess)
    261     # ScalarFunction caches. Reuse of fun(x) during grad
    262     # calculation reduces overall function evaluations.
--> 263     sf = ScalarFunction(fun, x0, args, grad, hess,
    264                         finite_diff_rel_step, bounds, epsilon=epsilon)
    265 

~/anaconda3/lib/python3.9/site-packages/scipy/optimize/_differentiable_functions.py in __init__(self, fun, x0, args, grad, hess, finite_diff_rel_step, finite_diff_bounds, epsilon)
    156 
    157         self._update_fun_impl = update_fun
--> 158         self._update_fun()
    159 
    160         # Gradient evaluation

~/anaconda3/lib/python3.9/site-packages/scipy/optimize/_differentiable_functions.py in _update_fun(self)
    249     def _update_fun(self):
    250         if not self.f_updated:
--> 251             self._update_fun_impl()
    252             self.f_updated = True
    253 

~/anaconda3/lib/python3.9/site-packages/scipy/optimize/_differentiable_functions.py in update_fun()
    153 
    154         def update_fun():
--> 155             self.f = fun_wrapped(self.x)
    156 
    157         self._update_fun_impl = update_fun

~/anaconda3/lib/python3.9/site-packages/scipy/optimize/_differentiable_functions.py in fun_wrapped(x)
    135             # Overwriting results in undefined behaviour because
    136             # fun(self.x) will change self.x, with the two no longer linked.
--> 137             fx = fun(np.copy(x), *args)
    138             # Make sure the function returns a true scalar
    139             if not np.isscalar(fx):

~/anaconda3/lib/python3.9/site-packages/scipy/optimize/_optimize.py in __call__(self, x, *args)
     74     def __call__(self, x, *args):
     75         """ returns the the function value """
---> 76         self._compute_if_needed(x, *args)
     77         return self._value
     78 

~/anaconda3/lib/python3.9/site-packages/scipy/optimize/_optimize.py in _compute_if_needed(self, x, *args)
     68         if not np.all(x == self.x) or self._value is None or self.jac is None:
     69             self.x = np.asarray(x).copy()
---> 70             fg = self.fun(x, *args)
     71             self.jac = fg[1]
     72             self._value = fg[0]

~/anaconda3/lib/python3.9/site-packages/gpflow/optimizers/scipy.py in _eval(x)
    222 
    223         def _eval(x: AnyNDArray) -> Tuple[AnyNDArray, AnyNDArray]:
--> 224             loss, grad = _tf_eval(tf.convert_to_tensor(x))
    225             return loss.numpy().astype(np.float64), grad.numpy().astype(np.float64)
    226 

~/anaconda3/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py in error_handler(*args, **kwargs)
    151     except Exception as e:
    152       filtered_tb = _process_traceback_frames(e.__traceback__)
--> 153       raise e.with_traceback(filtered_tb) from None
    154     finally:
    155       del filtered_tb

~/anaconda3/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py in autograph_handler(*args, **kwargs)
   1127           except Exception as e:  # pylint:disable=broad-except
   1128             if hasattr(e, "ag_error_metadata"):
-> 1129               raise e.ag_error_metadata.to_exception(e)
   1130             else:
   1131               raise

ValueError: in user code:

    File "/home/is2961/anaconda3/lib/python3.9/site-packages/gpflow/optimizers/scipy.py", line 192, in _tf_eval  *
        loss, grads = _compute_loss_and_gradients(
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/gpflow/optimizers/scipy.py", line 329, in _compute_loss_and_gradients  *
        loss = loss_closure()
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/gpflow/models/training_mixins.py", line 142, in closure  *
        return training_loss(data)
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/check_shapes/integration/tf.py", line 96, in wrapped_method  *
        return wrapped_function(self, *args, **kwargs)
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/check_shapes/decorator.py", line 121, in wrapped_function  *
        if not get_enable_check_shapes():
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/gpflow/models/training_mixins.py", line 107, in training_loss  *
        return self._training_loss(data)  # type: ignore[attr-defined]
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/check_shapes/integration/tf.py", line 96, in wrapped_method  *
        return wrapped_function(self, *args, **kwargs)
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/check_shapes/decorator.py", line 121, in wrapped_function  *
        if not get_enable_check_shapes():
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/gpflow/models/model.py", line 76, in _training_loss  *
        return -(self.maximum_log_likelihood_objective(*args, **kwargs) + self.log_prior_density())
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/check_shapes/integration/tf.py", line 96, in wrapped_method  *
        return wrapped_function(self, *args, **kwargs)
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/check_shapes/decorator.py", line 121, in wrapped_function  *
        if not get_enable_check_shapes():
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/gpflow/models/svgp.py", line 161, in maximum_log_likelihood_objective  *
        return self.elbo(data)
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/check_shapes/integration/tf.py", line 96, in wrapped_method  *
        return wrapped_function(self, *args, **kwargs)
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/check_shapes/decorator.py", line 121, in wrapped_function  *
        if not get_enable_check_shapes():
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/gpflow/models/svgp.py", line 174, in elbo  *
        var_exp = self.likelihood.variational_expectations(X, f_mean, f_var, Y)
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/check_shapes/integration/tf.py", line 96, in wrapped_method  *
        return wrapped_function(self, *args, **kwargs)
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/check_shapes/decorator.py", line 121, in wrapped_function  *
        if not get_enable_check_shapes():
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/gpflow/likelihoods/base.py", line 263, in variational_expectations  *
        return self._variational_expectations(X, Fmu, Fvar, Y)
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/check_shapes/integration/tf.py", line 96, in wrapped_method  *
        return wrapped_function(self, *args, **kwargs)
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/check_shapes/decorator.py", line 121, in wrapped_function  *
        if not get_enable_check_shapes():
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/gpflow/likelihoods/multiclass.py", line 194, in _variational_expectations  *
        p = self.invlink.prob_is_largest(Y, Fmu, Fvar, gh_x, gh_w)
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/check_shapes/integration/tf.py", line 96, in wrapped_method  *
        return wrapped_function(self, *args, **kwargs)
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/check_shapes/decorator.py", line 121, in wrapped_function  *
        if not get_enable_check_shapes():
    File "/home/is2961/anaconda3/lib/python3.9/site-packages/gpflow/likelihoods/multiclass.py", line 132, in prob_is_largest  *
        mu_selected = tf.reduce_sum(oh_on * mu, 1)

    ValueError: Dimensions must be equal, but are 6 and 2 for '{{node mul_13}} = Mul[T=DT_DOUBLE](Cast_2, add_10)' with input shapes: [6,3], [2,3].```

## Expected behavior

It shouldn't be treating the labels (Y) as the class labels, but rather the probabilities of each class (i.e. in hard label case, inputs should be one-hot vectors).

## System information

* GPflow version: 2.9.2
* GPflow installed from: pip install gpflow
* TensorFlow version: 2.7.0
* Python version:  3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0]
* Operating system: Ubuntu 22.04.5 LTS 

## Additional context

<!-- Add any other context about the problem here. -->

**Comment by Riccardo231** [comment]
Hello, I'd be glad to contribute to the project by fixing the issue. Can you assign it to me? Thanks

**Comment by uri-granta** [comment]
Sorry for not getting round to looking at this last year! Do feel free to submit a pull request if you think you have a fix (see https://github.com/GPflow/GPflow/blob/develop/CONTRIBUTING.md for some relevant info). 

In the meantime, could you please clarify the issue for me? I see that the code is crashing due to an assumption about one-hot encoding in RobustMax. Unfortunately I'm not familiar with this bit of the code. How exactly are you specifying the soft labels? And what makes you think that this is currently supported?
