### ISSUE TITLE
Installation fails: could not import setuptools

### ISSUE THREAD

**Issue by fonnesbeck** [GPflow/GPflow#250]
I've set up a Tensorflow-specific virtualenv using Anaconda, and installed Tensorflow, but when I go to import GPflow, I get the following:

```
Collecting git+https://github.com/GPflow/GPflow.git
  Cloning https://github.com/GPflow/GPflow.git to /var/folders/z_/kgsm76k94s7_jhnkfydfnd380000gn/T/pip-5tpkh_vm-build
Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
  File "/Users/fonnescj/anaconda3/envs/tensorflow/lib/python3.5/site-packages/pip/req/req_install.py", line 372, in setup_py
    import setuptools  # noqa
  File "/Users/fonnescj/anaconda3/envs/tensorflow/lib/python3.5/site-packages/setuptools/__init__.py", line 13, in <module>
    from setuptools.extension import Extension
  File "/Users/fonnescj/anaconda3/envs/tensorflow/lib/python3.5/site-packages/setuptools/extension.py", line 9, in <module>
    from .monkey import get_unpatched
ImportError: No module named 'setuptools.monkey'
```

However, I have confirmed that setuptools is indeed installed. This occurs both when trying to install via `python setup.py develop` and by using `pip` with the GitHub master branch.

Running Python 3.5.2 on macOS 10.12.

**Comment by fonnesbeck** [comment]
OK, my conda install gave me 26.1.1, even when I try to update it. If I force it via:

    conda install -c anaconda setuptools=27.2.0

that does the trick. Thanks.
