### ISSUE TITLE
Error testing GPFlow

### ISSUE THREAD

**Issue by mfrate28** [GPflow/GPflow#375]
Hi,

I'm having trouble running the tests (and importing) on my mac, but installations seems fine. The issue seems similar to other reported issues (#173, #227) but I haven't heard of having this happen on a mac.

python setup.py test
.....
running build_ext
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    'Topic :: Scientific/Engineering :: Artificial Intelligence']
  File "anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "anaconda2/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/setuptools/command/test.py", line 170, in run
  File "anaconda2/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/setuptools/command/test.py", line 191, in run_tests
  File "anaconda2/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "anaconda2/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "anaconda2/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "anaconda2/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "anaconda2/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "anaconda2/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/setuptools/command/test.py", line 39, in loadTestsFromModule
  File "anaconda2/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "Desktop/GPflow/testing/test_autoflow.py", line 1, in <module>
    import GPflow
  File "Desktop/GPflow/GPflow/__init__.py", line 18, in <module>
    from . import (likelihoods, kernels, ekernels, param, model, gpmc, sgpmc, priors, gpr, svgp, vgp, sgpr, gplvm, tf_wraps,
  File "Desktop/GPflow/GPflow/likelihoods.py", line 17, in <module>
    from . import densities, transforms
  File "Desktop/GPflow/GPflow/transforms.py", line 18, in <module>
    from . import tf_wraps as tfw
  File "Desktop/GPflow/GPflow/tf_wraps.py", line 33, in <module>
    _custom_op_module = tf.load_op_library(os.path.join(os.path.dirname(__file__), 'tfops', 'matpackops.so'))
  File "anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(Desktop/GPflow/GPflow/tfops/matpackops.so, 6): Symbol not found: __ZN10tensorflow7strings6StrCatB5cxx11ERKNS0_8AlphaNumE
  Referenced from: Desktop/GPflow/GPflow/tfops/matpackops.so
  Expected in: flat namespace
 in Desktop/GPflow/GPflow/tfops/matpackops.so

tensorflow 1.0.1 installed from pip
python 2.7.12
macOS 10.12.3
xcode 8.2.1

Thanks!

**Comment by jameshensman** [comment]
Did you build your own pip package or did you use the one on pypi?

There's an issue where the google-build uses (used?)  gcc4, and if your system is using gcc5 there's a missing symbol somewhere. To work around this, we add an extra flag in setup.py if the local version of gcc is 5. 

Problem is, if tensorflow was built with gcc 5 (as in, on your own machine) then adding this flag causes the symbols not found error like you describe.

**Comment by mfrate28** [comment]
I tried both the master branch and tag 0.3.4 from GitHub and installed with python setup.py develop. 
If its this line as mentioned in the other issues: 
if gcc_version > 4:
    compile_command += " -D_GLIBCXX_USE_CXX11_ABI=0"
Its not run by default because I'm on a mac, but I did try adding that and gets me a seg fault

**Comment by jameshensman** [comment]
Hmm, tricky. 

I suspect that the best way to get this working is to build your own tensorflow whl file, and then compile GPflow against that. 

could you let use know the output of `gcc --version` please

**Comment by mfrate28** [comment]
Sure, its:
gcc (GCC) 5.1.0

**Comment by jameshensman** [comment]
Could you simlink clang back in whilst compiling GPflow?

Works on my mabbook pro, late 2013, Sierra, using

gcc --version
<snip>
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.1.0

**Comment by mfrate28** [comment]
Ah I must have at some points unlinked gcc and clang - got it working now! Thanks!

**Comment by jameshensman** [comment]
Super, glad to be able to help.

**Comment by chughta1** [comment]
Sorry for bumping up and old thread but can i ask how this issue was fixed? Im on a MacBook Pro at the moment and have trouble testing GPflow. Since I am a bit of an OS X newbie Im not sure how I should link gcc and clang, which seems to be the aforementioned solution. Any help would be appreciated!

**Comment by alexggmatthews** [comment]
@chughta1 if you are using the most recent version of GPflow it shouldn't be necessary to compile anything. We removed the user ops that needed compiling in favour of a pure standard TensorFlow implementation of the relevant part. Let us know if you keep having problems.

**Comment by chughta1** [comment]
`running test
running egg_info
writing requirements to GPflow.egg-info/requires.txt
writing GPflow.egg-info/PKG-INFO
writing top-level names to GPflow.egg-info/top_level.txt
writing dependency_links to GPflow.egg-info/dependency_links.txt
reading manifest file 'GPflow.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'GPflow/tfops/*.so'
warning: no files found matching 'GPflow/tfops/*.cc'
writing manifest file 'GPflow.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    'Topic :: Scientific/Engineering :: Artificial Intelligence']
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/umarchughtai/tensorflow/lib/python2.7/site-packages/setuptools/command/test.py", line 215, in run
    self.run_tests()
  File "/Users/umarchughtai/tensorflow/lib/python2.7/site-packages/setuptools/command/test.py", line 238, in run_tests
    **exit_kwarg
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/Users/umarchughtai/tensorflow/lib/python2.7/site-packages/setuptools/command/test.py", line 43, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_notebooks'`

This is what I get when I run `python setup.py test`

**Comment by alexggmatthews** [comment]
So we're clear. What version of GPflow are you running?

**Comment by chughta1** [comment]
0.3.8,  installed it just a few days ago

**Comment by alexggmatthews** [comment]
Ok so the warnings you posted  look like the are coming from MANIFEST.in .I've filed a bug for that: #474 My apologies. 

I'm not currently sure if the error you are getting is directly related to the warnings. What happens if you delete the lines

```
include GPflow/tfops/*.so
include GPflow/tfops/*.cc
```

from [MANIFEST.in](https://github.com/GPflow/GPflow/blob/master/MANIFEST.in) then reinstall?

**Comment by chughta1** [comment]
The output when I run `python setup.py develop` again:

`running develop
running egg_info
writing requirements to GPflow.egg-info/requires.txt
writing GPflow.egg-info/PKG-INFO
writing top-level names to GPflow.egg-info/top_level.txt
writing dependency_links to GPflow.egg-info/dependency_links.txt
reading manifest file 'GPflow.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'GPflow.egg-info/SOURCES.txt'
running build_ext
Creating /Users/umarchughtai/tensorflow/lib/python2.7/site-packages/GPflow.egg-link (link to .)
GPflow 0.3.8 is already the active version in easy-install.pth

Installed /Users/umarchughtai/GP/GPflow
Processing dependencies for GPflow==0.3.8
Searching for pandas==0.20.3
Best match: pandas 0.20.3
Processing pandas-0.20.3-py2.7-macosx-10.12-x86_64.egg
pandas 0.20.3 is already the active version in easy-install.pth

Using /Users/umarchughtai/tensorflow/lib/python2.7/site-packages/pandas-0.20.3-py2.7-macosx-10.12-x86_64.egg
Searching for scipy==0.19.1
Best match: scipy 0.19.1
scipy 0.19.1 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/site-packages
Searching for numpy==1.13.1
Best match: numpy 1.13.1
Removing numpy 1.12.0 from easy-install.pth file
Adding numpy 1.13.1 to easy-install.pth file

Using /Users/umarchughtai/tensorflow/lib/python2.7/site-packages
Searching for pytz==2017.2
Best match: pytz 2017.2
Adding pytz 2017.2 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Searching for python-dateutil==2.6.0
Best match: python-dateutil 2.6.0
python-dateutil 2.6.0 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/site-packages
Searching for six==1.10.0
Best match: six 1.10.0
six 1.10.0 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/site-packages
Finished processing dependencies for GPflow==0.3.8`

The output when I run `python setup.py test`:

`running test
running egg_info
writing requirements to GPflow.egg-info/requires.txt
writing GPflow.egg-info/PKG-INFO
writing top-level names to GPflow.egg-info/top_level.txt
writing dependency_links to GPflow.egg-info/dependency_links.txt
reading manifest file 'GPflow.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'GPflow.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    'Topic :: Scientific/Engineering :: Artificial Intelligence']
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/umarchughtai/tensorflow/lib/python2.7/site-packages/setuptools/command/test.py", line 215, in run
    self.run_tests()
  File "/Users/umarchughtai/tensorflow/lib/python2.7/site-packages/setuptools/command/test.py", line 238, in run_tests
    **exit_kwarg
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/Users/umarchughtai/tensorflow/lib/python2.7/site-packages/setuptools/command/test.py", line 43, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_notebooks'`

:/

**Comment by alexggmatthews** [comment]
So the warnings have gone but not the error.

**Comment by alexggmatthews** [comment]
I suspect this is not a blocker to using GPflow but an error with the tests themselves. I would like to get it sorted but in the meantime I don't think it should stop you trying the software. 

Have you tried using the notebooks https://github.com/GPflow/GPflow/tree/master/doc/source/notebooks

**Comment by icouckuy** [comment]
This is most likely that the test dependencies have not be installed.

I first had the same error until I realised I was running my (empty) python 2 environment. Using my gpflowopt env everything works perfectly. Does running the notebooks require some extensions (at least jupyter/nbconvert needs to be there I assume, etc.)?

We have the test deps in setup.py:
'test': ['nose', 'coverage', 'six', 'parameterized']}

Most likely similar to GPflow (except paramterized you don't need), and I see we are missing jupyter (we have that in the doc deps) which you need also.

**Comment by chughta1** [comment]
@alexggmatthews I tried using the tutorials on: 

http://gpflow.readthedocs.io/en/latest/notebooks/regression.html

but some of the functions like
 `m.mean_function.A.prior = GPflow.priors.Gaussian(0., 10.)
m.mean_function.b.prior = GPflow.priors.Gaussian(0., 10.)`

dont work.

@icouckuy So how would make the gpflowopt env as my active environment?

**Comment by icouckuy** [comment]
With gpflowopt env I meant the virtualenv that I installed locally for running GPflowOpt. I see you are using anaconda on mac, so just make sure you have installed all the latest dependencies using pip, including jupyter.
pip install -U -e .
pip install -U jupyter nbconvert

Normally an anaconda env includes jupyter so I'm not sure which dependencies you are missing for running the notebook tests.

What error do you get with the above tutorial (please always provide a full error/stacktrace so we  can  help you better)?

**Comment by chughta1** [comment]
So i installed the jupyter dependency using pip, but I still get the note book error

here is what I get when I run the regression tutorial in my file GP.py:

`Traceback (most recent call last):
  File "GP.py", line 22, in <module>
    m.mean_function.A.prior = GPflow.priors.Gaussian(0., 10.)
  File "/Users/umarchughtai/GP/GPflow/GPflow/param.py", line 636, in __getattribute__
    o = object.__getattribute__(self, key)
AttributeError: 'Zero' object has no attribute 'A'`

Not to mention none of the plotting functions work, even with a virtual environment
