### ISSUE TITLE
Multi-dimensional GP with GPflow

### ISSUE THREAD

**Issue by mohaghasemzadeh** [GPflow/GPflow#449]
Hi,

I get the following error when trying to run my code. It should be clear for the developers, but I can't find any information about how to implement my model in GPflow. This is the same code from the tutorials, I just have increased the input dimensions to 8 instead of one.

My code:

k = GPflow.kernels.Matern32(input_dim=8, variance=1.0, active_dims=[0,1,2,3,4,5,6,7], ARD=True) + GPflow.kernels.Bias(1)
l = GPflow.likelihoods.Exponential()
m = GPflow.gpmc.GPMC(Xin, Yin, k, l, num_latent=1)

m.kern.matern32.lengthscales.prior = GPflow.priors.Gamma(1., 1.)
m.kern.matern32.variance.prior = GPflow.priors.Gamma(1.,1.)
m.kern.bias.variance.prior = GPflow.priors.Gamma(1.,1.)

m.optimize(maxiter=15) # start near MAP
samples = m.sample(100, verbose=False, epsilon=0.12, Lmax=15)

What I get:

Traceback (most recent call last):
  File "HMCGPU.py", line 22, in <module>
    m.optimize(maxiter=15) # start near MAP
  File "/usr/local/lib/python2.7/dist-packages/GPflow-0.3.8-py2.7.egg/GPflow/model.py", line 222, in optimize
    return self._optimize_np(method, tol, callback, maxiter, **kw)
  File "/usr/local/lib/python2.7/dist-packages/GPflow-0.3.8-py2.7.egg/GPflow/model.py", line 307, in _optimize_np
    options=options)
  File "/home/hamid/.local/lib/python2.7/site-packages/scipy/optimize/_minimize.py", line 450, in minimize
    callback=callback, **options)
  File "/home/hamid/.local/lib/python2.7/site-packages/scipy/optimize/lbfgsb.py", line 328, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/home/hamid/.local/lib/python2.7/site-packages/scipy/optimize/lbfgsb.py", line 278, in func_and_grad
    f = fun(x, *args)
  File "/home/hamid/.local/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 292, in function_wrapper
    return function(*(wrapper_args + args))
  File "/home/hamid/.local/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 63, in __call__
    fg = self.fun(x, *args)
  File "/usr/local/lib/python2.7/dist-packages/GPflow-0.3.8-py2.7.egg/GPflow/model.py", line 42, in __call__
    f, g = self._objective(x)
  File "/usr/local/lib/python2.7/dist-packages/GPflow-0.3.8-py2.7.egg/GPflow/model.py", line 160, in obj
    feed_dict=feed_dict)
  File "/home/hamid/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/hamid/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/hamid/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/hamid/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Got info = 24 for batch index 0, expected info = 0. Debug_info =potrf
	 [[Node: model.build_likelihood/Cholesky = Cholesky[T=DT_DOUBLE, _device="/job:localhost/replica:0/task:0/gpu:0"](model.build_likelihood/add)]]
	 [[Node: gradients/model.build_likelihood/MatMul_grad/MatMul/_23 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_770_gradients/model.build_likelihood/MatMul_grad/MatMul", tensor_type=DT_DOUBLE, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'model.build_likelihood/Cholesky', defined at:
  File "HMCGPU.py", line 22, in <module>
    m.optimize(maxiter=15) # start near MAP
  File "/usr/local/lib/python2.7/dist-packages/GPflow-0.3.8-py2.7.egg/GPflow/model.py", line 222, in optimize
    return self._optimize_np(method, tol, callback, maxiter, **kw)
  File "/usr/local/lib/python2.7/dist-packages/GPflow-0.3.8-py2.7.egg/GPflow/model.py", line 283, in _optimize_np
    self._compile()
  File "/usr/local/lib/python2.7/dist-packages/GPflow-0.3.8-py2.7.egg/GPflow/gpmc.py", line 67, in _compile
    super(GPMC, self)._compile()
  File "/usr/local/lib/python2.7/dist-packages/GPflow-0.3.8-py2.7.egg/GPflow/model.py", line 132, in _compile
    f = self.build_likelihood() + self.build_prior()
  File "/usr/local/lib/python2.7/dist-packages/GPflow-0.3.8-py2.7.egg/GPflow/scoping.py", line 43, in runnable
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/GPflow-0.3.8-py2.7.egg/GPflow/gpmc.py", line 78, in build_likelihood
    L = tf.cholesky(K + tf.eye(tf.shape(self.X)[0], dtype=float_type)*settings.numerics.jitter_level)
  File "/home/hamid/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_linalg_ops.py", line 227, in cholesky
    result = _op_def_lib.apply_op("Cholesky", input=input, name=name)
  File "/home/hamid/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/hamid/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/hamid/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Got info = 24 for batch index 0, expected info = 0. Debug_info =potrf
	 [[Node: model.build_likelihood/Cholesky = Cholesky[T=DT_DOUBLE, _device="/job:localhost/replica:0/task:0/gpu:0"](model.build_likelihood/add)]]
	 [[Node: gradients/model.build_likelihood/MatMul_grad/MatMul/_23 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_770_gradients/model.build_likelihood/MatMul_grad/MatMul", tensor_type=DT_DOUBLE, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by mohaghasemzadeh** [comment]
I just found out that if I increase the number of samples to 1-5, the code works perfectly, but any number of HMC samples over 5 throws a similar error. I am guessing GPFlow makes a poor usage of memory so it can't handle more than specific number of samples as data dimensionality is increased. Any help would be appreciated.

**Comment by mohaghasemzadeh** [comment]
Problem Solved!
