### ISSUE TITLE
Installation error: RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by DiegoRomeres** [GPflow/GPflow#476]
I am trying to install GPflow and I have Ubuntu 16.04 LTS.

I successfully installed tensorflow then I cloned the GPflow git repository in a local folder and then from that folder I executed

`sudo python setup.py develop`

But I got the following error:

running develop

    Traceback (most recent call last):
      File "setup.py", line 46, in <module>
        'Topic :: Scientific/Engineering :: Artificial Intelligence']
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 971, in run_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/develop.py", line 54, in finalize_options
        easy_install.finalize_options(self)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 333, in finalize_options
        self.index_url, search_path=self.shadow_path, hosts=hosts,
      File "/usr/local/lib/python2.7/dist-packages/setuptools/package_index.py", line 296, in __init__
        Environment.__init__(self, *args, **kw)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1055, in __init__
        self.scan(search_path)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1084, in scan
        for dist in find_distributions(item):
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048, in find_on_path
        for item in dists:
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2034, in find_on_path
        path_item, entry, metadata, precedence=DEVELOP_DIST
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2463, in from_location
        py_version=py_version, platform=platform, **kw
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2442, in __init__
        self._version = safe_version(version)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1391, in safe_version
        return str(packaging.version.Version(version))
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/_vendor/packaging/version.py", line 230, in __init__
        self._version.local,
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/_vendor/packaging/version.py", line 353, in _cmpkey
        reversed(release),
    RuntimeError: maximum recursion depth exceeded`

The error probably is in 

File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2048

but I do not know how to solve it. Any help is appreciated.

**Comment by mrksr** [comment]
Does this happen for the installation of other packages, too?
My first guess would be this has something to do with your local python installation. Looking at the [implementation](https://github.com/pypa/setuptools/blob/aa41a7a58d0e1cd0dd6715b2d4057666410114c7/pkg_resources/__init__.py#L2048), it might be an infinite loop constructed by a bad `.egg-link`-file (created, for example, by running `pip install -e`) somewhere in your `sys.path`.

**Comment by DiegoRomeres** [comment]
I installed other packages before with no problems, but, you are right, now I am experiencing the same problem while attempting to install any package. 
I did not execute `pip install -e` that I remember. Do you have any suggestion on how I could fix the problem?

**Comment by mrksr** [comment]
I have never heard of this problem, so I can only guess. I would first take a look at `sys.path` using a python interpreter and check if there is something strange. Then you could take a look at the `.egg-link`-files (which are human-readable) specifically using something like this (which is basically the short version of the code in `setuptools`):
```python
import os
import sys

def find_egg_links(path):
    if os.path.isdir(path):
        for item in os.listdir(path):
            if item.lower().endswith('.egg-link'):
                yield os.path.join(path, item)

[list(find_egg_links(path)) for path in sys.path]
```
Maybe this will help you in pinpointing the problem.

**Comment by DiegoRomeres** [comment]
Thank you for the hints. I checked my sys.path and I have

```
>>> import sys
>>> print sys.path
['', '/homes/romeres/catkin_ws/devel/lib/python2.7/dist-packages', '/opt/ros/kinetic/lib/python2.7/dist-packages', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/homes/romeres/.local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0']
```
and if I run your code I obtain
`
[[], [], [], [], [], [], [], [], [], ['/usr/local/lib/python2.7/dist-packages/tensorflow.egg-link'], ['/usr/local/lib/python2.7/dist-packages/tensorflow.egg-link'], [], [], []]`

In the beginning, the  initial empty path in sys.path and all the empty ones obtained from your code made me think that something was wrong, but looking to the print of others sys.path in some forum it seems to be standard. Besides that I do not see other problems.

**Comment by awav** [comment]
@DiegoRomeres, Hello, could you give more information which version of python, pip, GPflow, you are using. I ran `python setup.py develop` in `tensorflow/tensorflow` docker image and it works well.
```bash
root@3835e879a734:/notebooks/GPflow# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```,
```bash
root@3835e879a734:/notebooks/GPflow# python --version
Python 2.7.12
```,
```bash
root@3835e879a734:/notebooks/GPflow# pip --version
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
```,
```bash
oot@3835e879a734:/notebooks/GPflow# python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'1.2.1'
```

**Comment by DiegoRomeres** [comment]
Hello @awav, here there are my specifications:

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

```
$ python -V
Python 2.7.12
```
```
$ pip -V
pip 9.0.1 from /homes/romeres/.local/lib/python2.7/site-packages (python 2.7)
```
I installed GPflow following https://github.com/GPflow/GPflow .
When I run
`~/Repositories/GPflow$ sudo python setup.py develop`
I have the error that I mentioned before and of course if I try to import GPflow in a python interpreter I have the error:
`ImportError: No module named GPflow`
As @mrksr made me notice something has been probably corrupted in my local python installation because I cannot install anymore any other python package. But I do not know neither how to solve nor how to analyse it.

**Comment by mrksr** [comment]
Can you also show the contents of `/usr/local/lib/python2.7/dist-packages/tensorflow.egg-link`? Your `sys.path` looks quite complicated to me, but I do not see anything obvious.

**Comment by DiegoRomeres** [comment]
The tensorflow.egg-link is:
```
/usr/local/lib/python2.7/dist-packages
.
```

**Comment by mrksr** [comment]
Ah, that explains it. Python sees the `/usr/local/lib/python2.7/dist-packages/tensorflow.egg-link` and recurses into `/usr/local/lib/python2.7/dist-packages` to find packages to import. In this folder, it finds (besides other things), the file `/usr/local/lib/python2.7/dist-packages/tensorflow.egg-link`, which it reads and recurses into `/usr/local/lib/python2.7/dist-packages` to find packages to import. And so forth.

It should be safe to delete this file and things should work again, but maybe pip will not like that. I wonder how this happened?

**Comment by markvdw** [comment]
I assue this is fixed now. Feel free to re-open if it isn't.

**Comment by DiegoRomeres** [comment]
Yes, deleting the content of `/usr/local/lib/python2.7/dist-packages/tensorflow.egg-link` fixed the recursion problem. Thank you. (I do not know how this happened)
