### ISSUE TITLE
Issues in GP regression with the Matern Kernel. Is RBF more numerically stable than the Matern Kernel?

### ISSUE THREAD

**Issue by DiegoRomeres** [GPflow/GPflow#490]
I am doing GP regression with some real data dim(X)=[N,3] and dim[Y] = [N,1]. When I use the RBF Kernel it works fine when I use the Matern kernel it gives me some errors, probably in computing the cholesky during the optimazation. Here an idea of my code:

```
import GPflow

m = GPflow.gpr.GPR(X, Y, kern=GPflow.kernels.RBF(3))
m.optimize()


m2 = GPflow.gpr.GPR(X, Y, kern=GPflow.kernels.Matern52(3)+ GPflow.kernels.White(input_dim=3))
m2.optimize()
```
This is the error that I obtain

```
2017-08-21 17:49:05.142629: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-21 17:49:05.142639: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-21 17:49:05.142641: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-08-21 17:49:05.142643: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-21 17:49:05.142645: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-08-21 17:49:05.246520: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-08-21 17:49:05.246789: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.86
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.16GiB
2017-08-21 17:49:05.246798: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2017-08-21 17:49:05.246801: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2017-08-21 17:49:05.246806: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
2017-08-21 17:49:06.786071: I tensorflow/core/kernels/cuda_solvers.cc:137] Creating CudaSolver handles for stream 0x510a320
2017-08-21 17:49:11.326938: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
2017-08-21 17:49:13.169500: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Got info = 49 for batch index 0, expected info = 0. Debug_info =potrf
Traceback (most recent call last):
  File "/homes/romeres/.local/share/umake/ide/pycharm/helpers/pydev/pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/homes/romeres/.local/share/umake/ide/pycharm/helpers/pydev/pydevd.py", line 1023, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/homes/romeres/Projects/1DModelCodes/syncinputs_v2.py", line 177, in <module>
    m2.optimize()
  File "/usr/local/lib/python2.7/dist-packages/GPflow-0.3.8-py2.7.egg/GPflow/model.py", line 223, in optimize
    return self._optimize_np(method, tol, callback, maxiter, **kw)
  File "/usr/local/lib/python2.7/dist-packages/GPflow-0.3.8-py2.7.egg/GPflow/model.py", line 308, in _optimize_np
    options=options)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/_minimize.py", line 447, in minimize
    callback=callback, **options)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 330, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 278, in func_and_grad
    f = fun(x, *args)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 289, in function_wrapper
    return function(*(wrapper_args + args))
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 63, in __call__
    fg = self.fun(x, *args)
  File "/usr/local/lib/python2.7/dist-packages/GPflow-0.3.8-py2.7.egg/GPflow/model.py", line 43, in __call__
    f, g = self._objective(x)
  File "/usr/local/lib/python2.7/dist-packages/GPflow-0.3.8-py2.7.egg/GPflow/model.py", line 161, in obj
    feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Got info = 49 for batch index 0, expected info = 0. Debug_info =potrf
	 [[Node: name.build_likelihood/Cholesky = Cholesky[T=DT_DOUBLE, _device="/job:localhost/replica:0/task:0/gpu:0"](name.build_likelihood/add)]]
	 [[Node: name.build_likelihood/Cholesky/_27 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_394_name.build_likelihood/Cholesky", tensor_type=DT_DOUBLE, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'name.build_likelihood/Cholesky', defined at:
  File "/homes/romeres/.local/share/umake/ide/pycharm/helpers/pydev/pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/homes/romeres/.local/share/umake/ide/pycharm/helpers/pydev/pydevd.py", line 1023, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/homes/romeres/Projects/1DModelCodes/syncinputs_v2.py", line 177, in <module>
    m2.optimize()
  File "/usr/local/lib/python2.7/dist-packages/GPflow-0.3.8-py2.7.egg/GPflow/model.py", line 223, in optimize
    return self._optimize_np(method, tol, callback, maxiter, **kw)
  File "/usr/local/lib/python2.7/dist-packages/GPflow-0.3.8-py2.7.egg/GPflow/model.py", line 284, in _optimize_np
    self._compile()
  File "/usr/local/lib/python2.7/dist-packages/GPflow-0.3.8-py2.7.egg/GPflow/model.py", line 133, in _compile
    f = self.build_likelihood() + self.build_prior()
  File "/usr/local/lib/python2.7/dist-packages/GPflow-0.3.8-py2.7.egg/GPflow/scoping.py", line 43, in runnable
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/GPflow-0.3.8-py2.7.egg/GPflow/gpr.py", line 60, in build_likelihood
    L = tf.cholesky(K)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_linalg_ops.py", line 227, in cholesky
    result = _op_def_lib.apply_op("Cholesky", input=input, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Got info = 49 for batch index 0, expected info = 0. Debug_info =potrf
	 [[Node: name.build_likelihood/Cholesky = Cholesky[T=DT_DOUBLE, _device="/job:localhost/replica:0/task:0/gpu:0"](name.build_likelihood/add)]]
	 [[Node: name.build_likelihood/Cholesky/_27 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_394_name.build_likelihood/Cholesky", tensor_type=DT_DOUBLE, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]


Process finished with exit code 1
```

I obtained this error from the PyCharm console but from terminal it is analogous. Line 177 corresponds to m2.optimize().

As you can see I tried to add White noise to overcome possible numerical error.
I also tried to constrain the hyperparameters within a certain range but the result did not change.
```
m2.kern.matern52.lengthscales.transform = GPflow.transforms.Logistic(0.1, 10.)
m2.kern.matern52.variance.transform = GPflow.transforms.Logistic(0.1, 10.)
```
Am I missing something or is there a problem in the Matern kernel implementation?
Thank you in advance.

**Comment by mrksr** [comment]
Can you show us the result of `GPflow.settings.get_settings()`? Does the problem go away if you increase the `jitter_level`?

**Comment by markvdw** [comment]
@mrksr Unlike in `SVGP` or `SGPR`, the likelihood variance and jitter are effectively the same thing in `GPR`. As long as one ensures that the likelihood variance is bounded below by required jitter, one should be fine.

**Comment by mrksr** [comment]
Indeed. Thanks!

**Comment by DiegoRomeres** [comment]
Thank you for the help. This is the output of GPflow.settings.get_settings()

```
MutableNamedTuple([('verbosity', MutableNamedTuple([('tf_compile_verb', False), ('hmc_verb', True), ('optimisation_verb', False)])), ('dtypes', MutableNamedTuple([('float_type', tf.float64), ('int_type', tf.int32)])), ('numerics', MutableNamedTuple([('jitter_level', 1e-06), ('ekern_quadrature', 'warn')])), ('profiling', MutableNamedTuple([('dump_timeline', False), ('dump_tensorboard', False), ('output_file_name', 'timeline'), ('output_directory', './'), ('each_time', False)])), ('session', MutableNamedTuple([('intra_op_parallelism_threads', 0), ('inter_op_parallelism_threads', 0)]))])
Backend TkAgg is interactive backend. Turning interactive mode on.
MutableNamedTuple([('verbosity', MutableNamedTuple([('tf_compile_verb', False), ('hmc_verb', True), ('optimisation_verb', False)])), ('dtypes', MutableNamedTuple([('float_type', tf.float64), ('int_type', tf.int32)])), ('numerics', MutableNamedTuple([('jitter_level', 1e-06), ('ekern_quadrature', 'warn')])), ('profiling', MutableNamedTuple([('dump_timeline', False), ('dump_tensorboard', False), ('output_file_name', 'timeline'), ('output_directory', './'), ('each_time', False)])), ('session', MutableNamedTuple([('intra_op_parallelism_threads', 0), ('inter_op_parallelism_threads', 0)]))])
```
where it says that jitter_level =1e-6. Increasing the jitter level does  not help, I tried different values of it (even ridiculously high) with this code:
```
custom_config = GPflow.settings.get_settings()
custom_config.numerics.jitter_level = 1e2
with GPflow.settings.temp_settings(custom_config):
    m2 = GPflow.gpr.GPR(X, Y, kern=GPflow.kernels.Matern52(3) + GPflow.kernels.White(3))
    m2.optimize()
```
but the error remains.

**Comment by markvdw** [comment]
Like I said above, `GPR` does not use `jitter_level`. What precision are you using (`float32` or `float64`), and what does the variance of the `White` part of the kernel converge to?

**Comment by DiegoRomeres** [comment]
Sure, I only wanted to make it obvious with a numerical experiment. I am using float64. As for the variance of the noise I do not know how to check it since the optimization does not go through. Is there a way to see its value before the optimization procedure breaks?

**Comment by markvdw** [comment]
Ah yes, well you can change the lower bound of the transform, or you can force `optimize()` to quit early by passing it a `max_iters` (I think, check the scipy optimiser's docs) parameter. This should help you find out at what point it's going wrong.

**Comment by DiegoRomeres** [comment]
I tried all the standard scipy optimization routines and I imposed maxiter=1 to be safe as most as possible:

`m2.optimize(method = 'BFGS',maxiter=1)`
but no success.

**Comment by markvdw** [comment]
Try setting the White noise component variance to fixed? This will stop it from being optimised.

**Comment by mrksr** [comment]
This happens in the first iteration? If that is the case, check if you can successfully call `model.compute_log_likelihood()` before any optimization. Are you sure the data does not contain `NaN`-values and has the correct `dtype`? Does it contain duplicates? 

Does `Matern12` work? The only "real" difference to `RBF` is the `tf.sqrt` in [`euclid_dist`](https://github.com/GPflow/GPflow/blob/760ed24062b15f25a25e5caaad17028db7714a3b/GPflow/kernels.py#L344), which could maybe cause numerical issues.

**Comment by DiegoRomeres** [comment]
Thank you for the suggestions. I have been trying to play a bit with the kernels Matern12, Matern32, Matern52, with my data taking a smaller or bigger number of data and shuffling them and with the optimization routines. I would say that there is definitely a numerical problem.

None of the optimizer that I tried converge to a solution because they stopped for the error that i mentioned in my first post.
`
method = 'BFGS'` seems to be the most robust one I can make some iterations in the optimization from 1 to 20 depending on the data and the kernel.

The kernel Matern12 seems to be a bit more numerically robust w.r.t. Matern52.

I can call succesfully
`model.compute_log_likelihood()`

My data do not contain NaN-values. I am not sure what you mean buy duplicates, but I did not concatenate the same dataset multiple times.

Maybe my data are particularly difficult to model but isn't there a way to prevent these errors? Arbitrarily blocking the number of optimization is inconvenient and also not very scientific so I would prefer not to do that. All the models perform poorly in prediction since the optimization cannot really go through (also the RBF kernel even if it does not have error performs very poorly in prediction).

**Comment by hughsalimbeni** [comment]
c.f. #421

**Comment by FedericoV** [comment]
Have you tried normalizing your data?  Optimizers like SGD are highly
unstable when working with poorly conditioned datasets.  Something as
simple as setting the features to unit variance and zero mean might help a
lot.

**Comment by DiegoRomeres** [comment]
I tried both to normalize the data:

```
from sklearn import preprocessing

X_no_mean = X - X.mean(axis=0)
normalizer = preprocessing.Normalizer().fit(X_no_mean)
X = normalizer.transform(X_no_mean)
```

or to standardize the data:

```
scaler = preprocessing.StandardScaler().fit(X)
X = scaler.transform(X)
```

**Comment by hughsalimbeni** [comment]
Have you tried the `SafeMatern` with e.g. 1e-6?

**Comment by DiegoRomeres** [comment]
No, I did not know about this kernel. Is it a standard kernel in GPflow? Or do I have to download some external package? Because I cannot find it in the documentation.

**Comment by hughsalimbeni** [comment]
Sorry should have been more clear: I was referring to a small modification to the Matern I often use, which I posted in the discussion of a similar issue #421. Here it is again 

```python
class SafeMatern52(Matern52):
    def euclid_dist(self, X, X2):
        r2 = self.square_dist(X, X2)
        return tf.sqrt(r2 + 1e-6)  # I find 1e-12 is too small
```

**Comment by awav** [comment]
@hughsalimbeni ideally, the noise value should depend on float type which you use. Guess, by default it is `float32`, then precision is about 7 digits and `1e-12` does not make much sense.

**Comment by hughsalimbeni** [comment]
@awav Agreed, it should be float type dependent. Though in my experience I still find a problem with `1e-12`, even in `float64`. I think `1e-9` is generally OK, but I have't run any experiments to confirm this.

**Comment by hughsalimbeni** [comment]
Or (following a suggestion from @st--), how about `tf.sqrt(tf.abs(r2))`?

**Comment by DiegoRomeres** [comment]
It worked out thank you for the help. Both solution with `tf.sqrt(r2 + 1e-6)` and `tf.sqrt(tf.abs(r2))` worked well.

Additional notes:
The kernel with `tf.sqrt(tf.abs(r2))` performed slightly better in prediction but it was giving me this warning:
`Warning: inf or nan in gradient: replacing with zeros`

**Comment by BingqingLiu** [comment]
Hi Diego, I am currently working on GP regression and will need to use cholesky updates and downdates to compute covariance. May I ask if GPFlow already got this function, or do I have to include my own code?

**Comment by Zepp3** [comment]
@BingqingLiu I agree, would be nice if gpflow adds a save version of the matern kernels. As far as I see they are not yet included.
