### ISSUE TITLE
Changing parameter to fixed requires model recompilation prior to prediction 

### ISSUE THREAD

**Issue by alexisboukouvalas** [GPflow/GPflow#54]
Error is: ValueError: Cannot feed value of shape (4,) for Tensor u'Variable:0', which has shape '(5,)'
Error happens in predict_f  - full error trace below.

Minimal working example below.
Issue on master branch as of April 24, 2016.

### Code MWE - based on simple_regression.py
```
import GPflow
import tensorflow as tf
import os
import numpy as np
def getData():
    rng = np.random.RandomState( 1 )
    N = 30
    X = rng.rand(N,1)
    Y = np.sin(12*X) + 0.66*np.cos(25*X) + rng.randn(N,1)*0.1 + 3
    return X,Y
if __name__ == '__main__':
    X,Y = getData()
    k = GPflow.kernels.Matern52(1)
    meanf = GPflow.mean_functions.Linear(1,0)
    m = GPflow.gpr.GPR(X, Y, k, meanf)
    m.likelihood.variance = 0.01
    m._compile()
    print "Here are the parameters before optimization"
    print m
    m.kern.variance.fixed = True
    #m._compile() # If we compile again the code below works
    [mu,var] = m.predict_f(X)
    print mu
    print 'done'
```

### Trace:
```
Traceback (most recent call last):
  File "/Users/mqbssaby/PrivateProjects/BranchedGP/runfile.py", line 29, in <module>
    [mu,var] = m.predict_f(X)
  File "/Users/mqbssaby/pythonlibs/GPflow/GPflow/model.py", line 82, in runnable
    return instance._session.run(graph, feed_dict=feed_dict)
  File "/Users/mqbssaby/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/Users/mqbssaby/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 553, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (4,) for Tensor u'Variable:0', which has shape '(5,)'
```

**Comment by jameshensman** [comment]
@alexisboukouvalas , could you take a look at my PR and see if it successfully covers all your use cases? A little stress-testing would be very helpful.

**Comment by alexisboukouvalas** [comment]
this appears fixed and I haven't hit this issue again.
