### ISSUE TITLE
`InvalidArgumentError` when using ScipyOptimizer with SVGP

### ISSUE THREAD

**Issue by refrigerator** [GPflow/GPflow#588]
I'm trying to do the following:

```python
...
kernel = RBF(p) + White(1) + Constant(1)
self.model = SVGP(x, y, kern=kernel, likelihood=GPflow.likelihoods.Gaussian(), Z=z)
GPflow.train.ScipyOptimizer().minimize(self.model)
```

and am encountering this error:

```
InvalidArgumentError: assertion failed: [] [Condition x == y did not hold element-wise:] [x (13/SVGP/feature_conditional/strided_slice_1:0) = ] [5] [y (13/SVGP/feature_conditional/Const:0) = ] [6]
	 [[Node: 13/SVGP/feature_conditional/assert_equal/Assert/Assert = Assert[T=[DT_STRING, DT_STRING, DT_STRING, DT_INT32, DT_STRING, DT_INT32], summarize=3, _device="/job:localhost/replica:0/task:0/cpu:0"](13/SVGP/feature_conditional/assert_equal/All, 13/SVGP/feature_conditional/assert_equal/Assert/Assert/data_0, 13/SVGP/feature_conditional/assert_equal/Assert/Assert/data_1, 13/SVGP/feature_conditional/assert_equal/Assert/Assert/data_2, 13/SVGP/feature_conditional/strided_slice_1, 13/SVGP/feature_conditional/assert_equal/Assert/Assert/data_4, 13/SVGP/feature_conditional/Const)]]
```

Any idea what's going on?

Thanks

---

Here's the full traceback:
```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
~/virtualenvs/gpflow-test/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1326     try:
-> 1327       return fn(*args)
   1328     except errors.OpError as e:

~/virtualenvs/gpflow-test/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run_fn(session, feed_dict, fetch_list, target_list, options, run_metadata)
   1305                                    feed_dict, fetch_list, target_list,
-> 1306                                    status, run_metadata)
   1307 

/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     87             try:
---> 88                 next(self.gen)
     89             except StopIteration:

~/virtualenvs/gpflow-test/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py in raise_exception_on_not_ok_status()
    465           compat.as_text(pywrap_tensorflow.TF_Message(status)),
--> 466           pywrap_tensorflow.TF_GetCode(status))
    467   finally:

InvalidArgumentError: assertion failed: [] [Condition x == y did not hold element-wise:] [x (13/SVGP/feature_conditional/strided_slice_1:0) = ] [5] [y (13/SVGP/feature_conditional/Const:0) = ] [6]
	 [[Node: 13/SVGP/feature_conditional/assert_equal/Assert/Assert = Assert[T=[DT_STRING, DT_STRING, DT_STRING, DT_INT32, DT_STRING, DT_INT32], summarize=3, _device="/job:localhost/replica:0/task:0/cpu:0"](13/SVGP/feature_conditional/assert_equal/All, 13/SVGP/feature_conditional/assert_equal/Assert/Assert/data_0, 13/SVGP/feature_conditional/assert_equal/Assert/Assert/data_1, 13/SVGP/feature_conditional/assert_equal/Assert/Assert/data_2, 13/SVGP/feature_conditional/strided_slice_1, 13/SVGP/feature_conditional/assert_equal/Assert/Assert/data_4, 13/SVGP/feature_conditional/Const)]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-7-88f00e524803> in <module>()
----> 1 model.train(data)

~/workspace/research/analysis/gpflow-v1-release/notebooks/../src/models/svgp.py in train(self, data, y_feature, sample_size, inducing_points)
     64         x, y = self._vectorise(data, x_features, {y_feature})
     65         x, y = self._scale(x, y)
---> 66         self._fit(x, y, inducing_points)
     67 
     68     def predict(self, datum, return_std=True, y_feature='SalePrice', force=False):

~/workspace/research/analysis/gpflow-v1-release/notebooks/../src/models/svgp.py in _fit(self, x, y, m)
    158             Constant(1)
    159         self.model = SVGP(x, y, kern=kernel, likelihood=GPflow.likelihoods.Gaussian(), Z=z)
--> 160         GPflow.train.ScipyOptimizer().minimize(self.model)
    161 
    162     def _vectorise(self, data, x_features, y_feature):

~/virtualenvs/gpflow-test/lib/python3.6/site-packages/gpflow/training/scipy_optimizer.py in minimize(self, model, session, var_list, feed_dict, maxiter, initialize, anchor, **kwargs)
     68 
     69         feed_dict = self._gen_feed_dict(model, feed_dict)
---> 70         self._optimizer.minimize(session=session, feed_dict=feed_dict, **kwargs)
     71         if anchor:
     72             model.anchor(session)

~/virtualenvs/gpflow-test/lib/python3.6/site-packages/gpflow/training/external_optimizer.py in minimize(self, session, feed_dict, fetches, step_callback, loss_callback, **run_kwargs)
    173         packed_bounds=self._packed_bounds,
    174         step_callback=step_callback,
--> 175         optimizer_kwargs=self.optimizer_kwargs)
    176     var_vals = [
    177         packed_var_val[packing_slice] for packing_slice in self._packing_slices

~/virtualenvs/gpflow-test/lib/python3.6/site-packages/gpflow/training/external_optimizer.py in _minimize(self, initial_val, loss_grad_func, equality_funcs, equality_grad_funcs, inequality_funcs, inequality_grad_funcs, packed_bounds, step_callback, optimizer_kwargs)
    434 
    435     import scipy.optimize  # pylint: disable=g-import-not-at-top
--> 436     result = scipy.optimize.minimize(*minimize_args, **minimize_kwargs)
    437     logging.info('Optimization terminated with:\n'
    438                  '  Message: %s\n'

~/virtualenvs/gpflow-test/lib/python3.6/site-packages/scipy/optimize/_minimize.py in minimize(fun, x0, args, method, jac, hess, hessp, bounds, constraints, tol, callback, options)
    448     elif meth == 'l-bfgs-b':
    449         return _minimize_lbfgsb(fun, x0, args, jac, bounds,
--> 450                                 callback=callback, **options)
    451     elif meth == 'tnc':
    452         return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,

~/virtualenvs/gpflow-test/lib/python3.6/site-packages/scipy/optimize/lbfgsb.py in _minimize_lbfgsb(fun, x0, args, jac, bounds, disp, maxcor, ftol, gtol, eps, maxfun, maxiter, iprint, callback, maxls, **unknown_options)
    326             # until the completion of the current minimization iteration.
    327             # Overwrite f and g:
--> 328             f, g = func_and_grad(x)
    329         elif task_str.startswith(b'NEW_X'):
    330             # new iteration

~/virtualenvs/gpflow-test/lib/python3.6/site-packages/scipy/optimize/lbfgsb.py in func_and_grad(x)
    276     else:
    277         def func_and_grad(x):
--> 278             f = fun(x, *args)
    279             g = jac(x, *args)
    280             return f, g

~/virtualenvs/gpflow-test/lib/python3.6/site-packages/scipy/optimize/optimize.py in function_wrapper(*wrapper_args)
    290     def function_wrapper(*wrapper_args):
    291         ncalls[0] += 1
--> 292         return function(*(wrapper_args + args))
    293 
    294     return ncalls, function_wrapper

~/virtualenvs/gpflow-test/lib/python3.6/site-packages/scipy/optimize/optimize.py in __call__(self, x, *args)
     61     def __call__(self, x, *args):
     62         self.x = numpy.asarray(x).copy()
---> 63         fg = self.fun(x, *args)
     64         self.jac = fg[1]
     65         return fg[0]

~/virtualenvs/gpflow-test/lib/python3.6/site-packages/gpflow/training/external_optimizer.py in loss_grad_func_wrapper(x)
    396     def loss_grad_func_wrapper(x):
    397       # SciPy's L-BFGS-B Fortran implementation requires gradients as doubles.
--> 398       loss, gradient = loss_grad_func(x)
    399       return loss, gradient.astype('float64')
    400 

~/virtualenvs/gpflow-test/lib/python3.6/site-packages/gpflow/training/external_optimizer.py in eval_func(x)
    307 
    308       augmented_fetch_vals = session.run(
--> 309           augmented_fetches, feed_dict=augmented_feed_dict)
    310 
    311       if callable(callback):

~/virtualenvs/gpflow-test/lib/python3.6/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    893     try:
    894       result = self._run(None, fetches, feed_dict, options_ptr,
--> 895                          run_metadata_ptr)
    896       if run_metadata:
    897         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~/virtualenvs/gpflow-test/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1122     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1123       results = self._do_run(handle, final_targets, final_fetches,
-> 1124                              feed_dict_tensor, options, run_metadata)
   1125     else:
   1126       results = []

~/virtualenvs/gpflow-test/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1319     if handle is None:
   1320       return self._do_call(_run_fn, self._session, feeds, fetches, targets,
-> 1321                            options, run_metadata)
   1322     else:
   1323       return self._do_call(_prun_fn, self._session, handle, feeds, fetches)

~/virtualenvs/gpflow-test/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1338         except KeyError:
   1339           pass
-> 1340       raise type(e)(node_def, op, message)
   1341 
   1342   def _extend_graph(self):

InvalidArgumentError: assertion failed: [] [Condition x == y did not hold element-wise:] [x (13/SVGP/feature_conditional/strided_slice_1:0) = ] [5] [y (13/SVGP/feature_conditional/Const:0) = ] [6]
	 [[Node: 13/SVGP/feature_conditional/assert_equal/Assert/Assert = Assert[T=[DT_STRING, DT_STRING, DT_STRING, DT_INT32, DT_STRING, DT_INT32], summarize=3, _device="/job:localhost/replica:0/task:0/cpu:0"](13/SVGP/feature_conditional/assert_equal/All, 13/SVGP/feature_conditional/assert_equal/Assert/Assert/data_0, 13/SVGP/feature_conditional/assert_equal/Assert/Assert/data_1, 13/SVGP/feature_conditional/assert_equal/Assert/Assert/data_2, 13/SVGP/feature_conditional/strided_slice_1, 13/SVGP/feature_conditional/assert_equal/Assert/Assert/data_4, 13/SVGP/feature_conditional/Const)]]

Caused by op '13/SVGP/feature_conditional/assert_equal/Assert/Assert', defined at:
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2856, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-88f00e524803>", line 1, in <module>
    model.train(data)
  File "/Users/taimurabdaal/workspace/research/analysis/gpflow-v1-release/notebooks/../src/models/svgp.py", line 66, in train
    self._fit(x, y, inducing_points)
  File "/Users/taimurabdaal/workspace/research/analysis/gpflow-v1-release/notebooks/../src/models/svgp.py", line 159, in _fit
    self.model = SVGP(x, y, kern=kernel, likelihood=GPflow.likelihoods.Gaussian(), Z=z)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/gpflow/core/compilable.py", line 90, in __init__
    self.build()
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/gpflow/core/node.py", line 130, in build
    self._build()
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/gpflow/models/model.py", line 81, in _build
    likelihood = self._build_likelihood()
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/gpflow/decors.py", line 60, in tensor_mode_wrapper
    result = method(obj, *args, **kwargs)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/gpflow/models/svgp.py", line 117, in _build_likelihood
    fmean, fvar = self._build_predict(self.X, full_cov=False)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/gpflow/decors.py", line 60, in tensor_mode_wrapper
    result = method(obj, *args, **kwargs)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/gpflow/models/svgp.py", line 130, in _build_predict
    q_sqrt=self.q_sqrt, full_cov=full_cov, white=self.whiten)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/functools.py", line 803, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/gpflow/features.py", line 173, in default_feature_conditional
    white=white)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/gpflow/decors.py", line 42, in runnable
    return method(*args, **kwargs)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/gpflow/conditionals.py", line 70, in feature_conditional
    Kmm = feat.Kuu(kern, jitter=settings.numerics.jitter_level)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/gpflow/decors.py", line 60, in tensor_mode_wrapper
    result = method(obj, *args, **kwargs)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/gpflow/features.py", line 71, in Kuu
    Kzz = kern.K(self.Z)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/gpflow/kernels.py", line 834, in K
    return reduce(tf.add, [k.K(X, X2) for k in self.kern_list])
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/gpflow/kernels.py", line 834, in <listcomp>
    return reduce(tf.add, [k.K(X, X2) for k in self.kern_list])
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/gpflow/decors.py", line 60, in tensor_mode_wrapper
    result = method(obj, *args, **kwargs)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/gpflow/kernels.py", line 409, in K
    X, X2 = self._slice(X, X2)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/gpflow/kernels.py", line 251, in _slice
    with tf.control_dependencies([tf.assert_equal(input_dim_shape, input_dim)]):
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/tensorflow/python/ops/check_ops.py", line 318, in assert_equal
    return control_flow_ops.Assert(condition, data, summarize=summarize)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py", line 175, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 124, in Assert
    condition, data, summarize, name="Assert")
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 35, in _assert
    summarize=summarize, name=name)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/taimurabdaal/virtualenvs/gpflow-test/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): assertion failed: [] [Condition x == y did not hold element-wise:] [x (13/SVGP/feature_conditional/strided_slice_1:0) = ] [5] [y (13/SVGP/feature_conditional/Const:0) = ] [6]
	 [[Node: 13/SVGP/feature_conditional/assert_equal/Assert/Assert = Assert[T=[DT_STRING, DT_STRING, DT_STRING, DT_INT32, DT_STRING, DT_INT32], summarize=3, _device="/job:localhost/replica:0/task:0/cpu:0"](13/SVGP/feature_conditional/assert_equal/All, 13/SVGP/feature_conditional/assert_equal/Assert/Assert/data_0, 13/SVGP/feature_conditional/assert_equal/Assert/Assert/data_1, 13/SVGP/feature_conditional/assert_equal/Assert/Assert/data_2, 13/SVGP/feature_conditional/strided_slice_1, 13/SVGP/feature_conditional/assert_equal/Assert/Assert/data_4, 13/SVGP/feature_conditional/Const)]]
```

**Comment by refrigerator** [comment]
My bad — my RBF kernel had one too many dimensions!
