### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: /home/chaztikov/anaconda3/lib/python3.6/site-packages/GPflow/tfops/matpackops.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

### ISSUE THREAD

**Issue by Chaztikov** [GPflow/GPflow#594]
I installed through Anaconda

https://anaconda.org/omnia/gpflow

But have issues upon import:

Python 3.6.2 |Anaconda custom (64-bit)| (default, Jul 20 2017, 13:51:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gpflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'gpflow'
>>> import GPflow
/home/chaztikov/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chaztikov/anaconda3/lib/python3.6/site-packages/GPflow/__init__.py", line 18, in <module>
    from . import (likelihoods, kernels, ekernels, param, model, gpmc, sgpmc, priors, gpr, svgp, vgp, sgpr, gplvm, tf_wraps,
  File "/home/chaztikov/anaconda3/lib/python3.6/site-packages/GPflow/likelihoods.py", line 17, in <module>
    from . import densities, transforms
  File "/home/chaztikov/anaconda3/lib/python3.6/site-packages/GPflow/transforms.py", line 18, in <module>
    from . import tf_wraps as tfw
  File "/home/chaztikov/anaconda3/lib/python3.6/site-packages/GPflow/tf_wraps.py", line 33, in <module>
    _custom_op_module = tf.load_op_library(os.path.join(os.path.dirname(__file__), 'tfops', 'matpackops.so'))
  File "/home/chaztikov/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/chaztikov/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/chaztikov/anaconda3/lib/python3.6/site-packages/GPflow/tfops/matpackops.so: undefined symbol: _ZTIN10tensorflow8OpKernelE
>>> 

I was using an earlier version of GPflow with tensorflow, not sure what changed.  I have tensorflow-gpu=1.4 as well.

Any help is appreciated, as I am trying to update results I generated using GPflow ASAP

**Comment by Chaztikov** [comment]
Seems I resolved the issue by just installing from source via github.

Thanks!

**Comment by icouckuy** [comment]
Seems anaconda has an older version of GPflow where the module was still named with capitals GPFlow and has the shared library. Install the latest from git.
