### ISSUE TITLE
Unmaintained scripts in doc/source/notebooks

### ISSUE THREAD

**Issue by aneergaard** [GPflow/GPflow#748]
I get the following error when running the regression.py script in the notebooks folder: 
```Traceback (most recent call last):

  File "C:\Program Files\JetBrains\PyCharm 2017.3.4\helpers\pydev\pydevd.py", line 1668, in <module>
    main()

  File "C:\Program Files\JetBrains\PyCharm 2017.3.4\helpers\pydev\pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)

  File "C:\Program Files\JetBrains\PyCharm 2017.3.4\helpers\pydev\pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script

  File "C:\Program Files\JetBrains\PyCharm 2017.3.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile

    exec(compile(contents+"\n", file, 'exec'), glob, loc)

  File "C:/Users/neergaard/Repositories/GPflow/notebooks/simple_regression.py", line 59, in <module>
    runExperiments()

  File "C:/Users/neergaard/Repositories/GPflow/notebooks/simple_regression.py", line 54, in runExperiments

    setModelPriors(m)
  File "C:/Users/neergaard/Repositories/GPflow/notebooks/simple_regression.py", line 35, in setModelPriors

    m.kern.lengthscales.prior = gpflow.priors.Gamma(1., 1.)

  File "C:\Users\neergaard\Repositories\GPflow\gpflow\params\parameter.py", line 476, in __setattr__
    self._set_parameter_attribute(attr, value)

  File "C:\Users\neergaard\Repositories\GPflow\gpflow\params\parameter.py", line 465, in _set_parameter_attribute

    raise GPflowError('Parameter "{}" has already been compiled.'.format(self.pathname))

gpflow.core.errors.GPflowError: Parameter "GPR/kern/lengthscales" has already been compiled.
```

    * GPflow version or git commit (SHA hash) which you are using (e.g. `git rev-parse HEAD`): 1.1.1
    * Tensorflow version: 1.8.0
    * Does your tensorflow use GPU or not: GPU
    * Python version: 3.6.5
    * OS: Windows 10
    * PC, macbook configuration

**Comment by awav** [comment]
I'm not sure that this file is up-to-date and matches GPflow 1.* requirements. We don't tests it as well. @jameshensman, @markvdw, @alexggmatthews should we remove it?
@doktorneergaard , are you interested in something particular in this file?

**Comment by doktorneergaard** [comment]
@awav I actually wanted to use it to test how the library works, so no, nothing in particular. I'll close this issue for now.

**Comment by kingaza** [comment]
So, how to constrain parameters? 
The error like 'Parameter "Periodic/period" has already been compiled.' always happens.
thx

**Comment by st--** [comment]
@kingaza with a prior, the computational graph will be different. Tensorflow only has a static graph - so you can't change it. Hence, you will need to reset the graph: call `model.clear()`, then add the priors, then call `model.compile()` to re-build the graph.

**Comment by kingaza** [comment]
@st-- thank you very much~

**Comment by st--** [comment]
Unmaintained scripts have all been removed now.
