### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by ZezhouCheng** [GPflow/GPflow#850]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gpflow/__init__.py", line 19, in <module>
    from ._settings import SETTINGS as settings
  File "gpflow/_settings.py", line 198, in <module>
    __LOADED_SETTINGS = _namedtuplify(__CONFIG._sections)
  File "gpflow/_settings.py", line 162, in _namedtuplify
    mapping[key] = _namedtuplify(value)
  File "gpflow/_settings.py", line 162, in _namedtuplify
    mapping[key] = _namedtuplify(value)
  File "gpflow/_settings.py", line 169, in _namedtuplify
    return _parse(mapping)
  File "gpflow/_settings.py", line 135, in _parse
    .format(string))
ValueError: Config value "WARNING" expected to be string.

I downloaded the gpflow and run "pip install .", but encountered this issue when import gpflow

**Comment by ZezhouCheng** [comment]
> Traceback (most recent call last):
> File "", line 1, in 
> File "gpflow/**init**.py", line 19, in 
> from ._settings import SETTINGS as settings
> File "gpflow/_settings.py", line 198, in 
> __LOADED_SETTINGS = _namedtuplify(__CONFIG._sections)
> File "gpflow/_settings.py", line 162, in _namedtuplify
> mapping[key] = _namedtuplify(value)
> File "gpflow/_settings.py", line 162, in _namedtuplify
> mapping[key] = _namedtuplify(value)
> File "gpflow/_settings.py", line 169, in _namedtuplify
> return _parse(mapping)
> File "gpflow/_settings.py", line 135, in _parse
> .format(string))
> ValueError: Config value "WARNING" expected to be string.
> 
> I downloaded the gpflow and run "pip install .", but encountered this issue when import gpflow

This problem is solved by switch to python 3.5. Sorry for my carelessness.
